- name: Download distro binary
  uri:
    url: https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro
    dest: /usr/bin/distro
    mode: 0755

- name: Install snmp packages
  yum: 
    name:
      - net-snmp
      - net-snmp-utils
    state: latest

- name: copy config file
  template:
    src: snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: 0600

- name: Start snmpd service
  service:
    name: snmpd
    state: started
    enabled: yes
